### PR TITLE
Fix field marshaller

### PR DESCRIPTION
**Pull request by instabledesign**

### CODE REVIEW

**Comment by instabledesign** [comment]
it will fix the `json.Marshall(errors.New("my_error")) // will return empty string`

**Comment by rmasclef** [comment]
so there was no issue with other objects ?

**Comment by instabledesign** [comment]
@rmasclef 
> so there was no issue with other objects ?

Which object have you in mind?

**Comment by rmasclef** [comment]
well any type of object actually 👍

what makes an Error object not directly JSON marshallable whereas other objects are ?

**Comment by nsitbon** [comment]
I'm don't really understand the problem and the solution neither... @rmasclef pay attention to the return type of `errors.New` : it's not an object but an interface maybe it's hint for the proposed solution (even though I don't understand it too)

**Pull request merged**
